server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watermark?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
      encoding: UTF-8

app:
  storage:
    base-url: http://localhost:9000
    bucket: watermark

